SELECT *
FROM Walmart_sales$
-- Finding Total Revenue Generated by Walmart

SELECT SUM(Weekly_Sales) as Total_Revenue
FROM Walmart_sales$

-- Finding the Total Revenue Generated by each store

SELECT Store, SUM(Weekly_Sales) as Total_Revenue
FROM Walmart_sales$
GROUP BY Store
ORDER BY Total_Revenue DESC

-- Weekly sales trend over time

SELECT Date, SUM(Weekly_Sales) as Total_Weekly_Sales
FROM Walmart_sales$
GROUP BY Date
ORDER BY Date

-- Impact of Holidays on Sales
SELECT Holiday_Flag, SUM(Weekly_Sales) as Total_Revenue
FROM Walmart_sales$
GROUP BY Holiday_Flag

-- Average Sales by Temperature Range

SELECT 
    CASE 
        WHEN Temperature < 30 THEN 'Below 30'
        WHEN Temperature BETWEEN 30 AND 60 THEN '30-60'
        WHEN Temperature BETWEEN 60 AND 90 THEN '60-90'
        ELSE 'Above 90'
    END AS Temperature_Range,
    AVG(Weekly_Sales) AS Average_Sales
FROM Walmart_sales$
GROUP BY 
    CASE 
        WHEN Temperature < 30 THEN 'Below 30'
        WHEN Temperature BETWEEN 30 AND 60 THEN '30-60'
        WHEN Temperature BETWEEN 60 AND 90 THEN '60-90'
        ELSE 'Above 90'
    END
ORDER BY Temperature_Range;
-- Average sales by temperature using common table expression
WITH TemperatureRanges AS (
    SELECT 
        *,
        CASE 
            WHEN Temperature < 30 THEN 'Below 30'
            WHEN Temperature BETWEEN 30 AND 60 THEN '30-60'
            WHEN Temperature BETWEEN 60 AND 90 THEN '60-90'
            ELSE 'Above 90'
        END AS Temperature_Range
    FROM Walmart_sales$
)
SELECT 
    Temperature_Range,
    AVG(Weekly_Sales) AS Average_Sales
FROM TemperatureRanges
GROUP BY Temperature_Range
ORDER BY Temperature_Range;


